# Credit Card Fraud Detection using Machine Learning

# About Data:
This is a dataset containing credit card transactions with 31 features and a class label. The features represent various aspects of the transaction, and the class label indicates whether the transaction was fraudulent (class 1) or not (class 0).

The first feature is "Time", which represents the number of seconds elapsed between the transaction and the first transaction in the dataset. The next 28 features, V1 to V28, are anonymized variables resulting from a principal component analysis (PCA) transformation of the original features. They represent different aspects of the transaction, such as the amount, location, and type of transaction.

The second last feature is "Amount", which represents the transaction amount in USD. The last feature is the "Class" label, which indicates whether the transaction is fraudulent (class 1) or not (class 0).

Overall, this dataset is used to train machine learning models to detect fraudulent transactions in real-time. The features are used to train the model to learn patterns in the data, which can then be used to detect fraudulent transactions in future transactions.

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
credit_card_data = pd.read_csv('test-4.csv')
credit_card_data.head()

,id,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-0.260648,-0.469648,2.496266,-0.083724,0.129681,0.732898,0.519014,-0.130006,0.727159,...,-0.110552,0.217606,-0.134794,0.165959,0.126280,-0.434824,-0.081230,-0.151045,17982.10,0
1,1,0.985100,-0.356045,0.558056,-0.429654,0.277140,0.428605,0.406466,-0.133118,0.347452,...,-0.194936,-0.605761,0.079469,-0.577395,0.190090,0.296503,-0.248052,-0.064512,6531.37,0
2,2,-0.260272,-0.949385,1.728538,-0.457986,0.074062,1.419481,0.743511,-0.095576,-0.261297,...,-0.005020,0.702906,0.945045,-1.154666,-0.605564,-0.312895,-0.300258,-0.244718,2513.54,0
3,3,-0.152152,-0.508959,1.746840,-1.090178,0.249486,1.143312,0.518269,-0.065130,-0.205698,...,-0.146927,-0.038212,-0.214048,-1.893131,1.003963,-0.515950,-0.165316,0.048424,5384.44,0
4,4,-0.206820,-0.165280,1.527053,-0.448293,0.106125,0.530549,0.658849,-0.212660,1.049921,...,-0.106984,0.729727,-0.161666,0.312561,-0.414116,1.071126,0.023712,0.419117,14278.97,0

In [3]:
credit_card_data.sample()

,id,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
7128,7128,0.904764,-0.616737,1.230644,-0.430939,-0.096479,0.546615,0.184914,-0.117618,2.596404,...,-0.243241,-0.554799,0.075115,0.186641,-0.091382,1.864618,-0.302563,-0.076686,3926.59,0

In [4]:
# dataset informations
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      7500 non-null   int64
 1   V1      7500 non-null   float64
 2   V2      7500 non-null   float64
 3   V3      7500 non-null   float64
 4   V4      7500 non-null   float64
 5   V5      7500 non-null   float64
 6   V6      7500 non-null   float64
 7   V7      7500 non-null   float64
 8   V8      7500 non-null   float64
 9   V9      7500 non-null   float64
 10  V10     7500 non-null   float64
 11  V11     7500 non-null   float64
 12  V12     7500 non-null   float64
 13  V13     7500 non-null   float64
 14  V14     7500 non-null   float64
 15  V15     7500 non-null   float64
 16  V16     7500 non-null   float64
 17  V17     7500 non-null   float64
 18  V18     7500 non-null   float64
 19  V19     7500 non-null   float64
 20  V20     7500 non-null   float64
 21  V21     7500 non-null   float64
 22  V22     7500 non-null   float64
 23  V23     7500 non-null   float64
 24  V24     7500 non-null   float64
 25  V25     7500 non-null   float64
 26  V26     7500 non-null   float64
 27  V27     7500 non-null   float64
 28  V28     7500 non-null   float64
 29  Amount  7500 non-null   float64
 30  Class   7500 non-null   int64
dtypes: float64(29), int64(2)
memory usage: 1.8 MB

In [5]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

id        0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [6]:
# distribution of legit transactions & fraudulent transactions
credit_card_data['Class'].value_counts()

Class
0    7475
1      25
Name: count, dtype: int64

This Dataset is highly unblanced

0 --> Normal Transaction

1 --> fraudulent transaction

The first line of code creates a new dataframe called "legit" by selecting only the rows from the original "credit_card_data" dataframe where the "Class" label is equal to 0. In other words, it filters out all transactions labeled as fraudulent (Class == 1) and keeps only the legitimate transactions (Class == 0).

The second line of code creates a new dataframe called "fraud" by selecting only the rows from the original "credit_card_data" dataframe where the "Class" label is equal to 1. This filters out all legitimate transactions and keeps only the fraudulent transactions.

By separating the data into two dataframes, it becomes easier to analyze and compare the characteristics of legitimate and fraudulent transactions separately. This can be useful for identifying patterns or features that are more common in fraudulent transactions, which can then be used to develop models for fraud detection.

In [7]:
legit = credit_card_data[credit_card_data.Class==0]
fraud = credit_card_data[credit_card_data['Class']==1]

In [8]:
fraud['Class']

541     1
623     1
4920    1
6108    1
6329    1
6331    1
6334    1
6336    1
6338    1
6427    1
6446    1
6472    1
6529    1
6609    1
6641    1
6717    1
6719    1
6734    1
6774    1
6820    1
6870    1
6882    1
6899    1
6903    1
6971    1
Name: Class, dtype: int64

In [9]:
# statistical measures of the data
legit.Amount.describe()

count     7475.000000
mean     11980.784062
std       6930.834270
min         50.530000
25%       5964.210000
50%      11819.710000
75%      18047.565000
max      24035.200000
Name: Amount, dtype: float64

In [10]:
fraud.Amount.describe()

count       25.000000
mean      8458.306400
std       5243.111838
min       1415.950000
25%       3875.510000
50%       9890.390000
75%      12162.550000
max      20487.280000
Name: Amount, dtype: float64

In [11]:
# compare the values for both transactions
credit_card_data.groupby('Class').mean()

,id,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,3741.802943,0.253756,-0.378376,1.143572,-0.650991,0.316449,0.53450,0.474093,-0.157364,0.997445,...,-0.127870,-0.132506,-0.173199,-0.049104,0.181071,0.080637,-0.102907,-0.192528,-0.101273,11980.784062
1,6050.920000,-0.040107,0.368566,-0.550948,0.811516,0.184242,-0.79313,0.001613,0.007280,-0.231929,...,0.080662,0.048478,-0.274943,-0.115910,-0.260672,0.131179,0.535532,0.341847,0.470742,8458.306400

Build a sample dataset containing similar distribution of normal transactions and Fraudulent Transactions

Number of Fraudulent Transactions --> 492

legit_sample = legit.sample(n=492) is a line of code that takes a random sample of 492 observations from the legit dataset. This is done to balance the number of observations in the legit and fraud datasets, which is necessary for training a machine learning model to predict fraud. Since the original dataset has a large number of legitimate transactions and a small number of fraudulent transactions, the model may be biased towards predicting that all transactions are legitimate. By creating a balanced dataset with an equal number of legitimate and fraudulent transactions, the model can be trained to better recognize the patterns that differentiate fraudulent transactions from legitimate ones

In [12]:
legit_sample = legit.sample(n=25)

In [13]:
new_df = pd.concat([legit_sample,fraud],axis=0)

In [14]:
new_df

,id,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
128,128,-0.610754,-0.149765,0.302544,-1.421330,0.286041,0.170879,0.469659,0.042772,0.741785,...,-0.270997,-0.563318,0.045425,-1.468704,-0.161036,1.478826,-0.298853,-1.130311,14760.58,0
28,28,0.029627,-0.156969,1.686545,-0.051448,0.256393,0.359752,0.721268,-0.159080,0.168199,...,-0.072341,0.391042,-0.062662,1.382419,-0.379041,-0.655254,-0.021582,0.268532,23323.50,0
2994,2994,1.005689,-0.311317,0.717422,-0.303302,0.090903,-0.279546,0.493904,-0.215264,0.413425,...,-0.204713,-0.653335,0.129627,1.510187,0.248351,0.173034,-0.258249,-0.008770,14098.01,0
3393,3393,-0.143532,-0.111575,0.999100,-1.935826,0.281870,-0.461033,0.898202,-0.269078,1.386969,...,-0.068953,0.450173,-0.266352,0.803263,0.059249,-2.293908,-0.322375,0.024324,4973.61,0
7422,7422,0.997534,-0.342724,0.912906,-0.307110,0.087697,0.031550,0.385952,-0.184436,1.251875,...,-0.244230,-0.736661,0.143571,0.987821,0.131187,0.075143,-0.305805,-0.090308,11748.73,0
1942,1942,-0.345661,0.064169,0.954720,-1.005471,0.035920,-0.037934,0.435495,-0.229325,0.850908,...,0.114849,-0.743604,0.099002,0.756800,-0.290592,0.668049,0.089233,0.497558,4931.93,0
3260,3260,0.013419,-0.237575,1.226350,-1.947241,0.396109,-0.016496,0.844823,-0.194349,0.828426,...,-0.040919,0.775316,-0.279963,0.508205,-0.159942,-2.198149,0.066544,-0.159552,23074.54,0
5779,5779,0.960974,-0.445771,1.176734,-0.187990,-0.018479,0.281216,0.285136,-0.183313,1.987363,...,-0.129922,0.223121,-0.147451,0.907639,0.740187,0.999925,-0.260431,-0.055551,17341.91,0
1906,1906,0.924651,-0.283614,0.817879,0.277407,0.175499,0.136590,0.515569,-0.180973,0.094080,...,-0.173689,-0.622220,0.033940,0.699917,0.463023,-0.437077,-0.261566,-0.024991,13139.10,0
3228,3228,-0.140111,-0.156173,1.052054,-1.997431,0.294758,0.051713,0.674685,-0.340592,1.186621,...,0.233818,0.370654,-0.134932,0.385115,-0.128379,-2.152113,0.231118,-0.001830,15979.11,0
1120,1120,-0.262455,-0.579480,2.915960,-0.427737,0.534868,0.518438,0.418194,-0.224168,0.961938,...,-0.192477,0.069198,-0.452074,0.159522,0.012166,0.799622,-0.708420,-0.981164,21462.49,0
5009,5009,0.052896,-0.119297,1.888796,-0.011702,0.265751,0.382726,0.710661,-0.193180,1.364895,...,-0.188041,0.086306,-0.114169,1.166567,-0.463686,-0.766318,0.040164,-0.151696,6006.30,0
3248,3248,0.020758,-0.209638,1.327249,-1.811855,0.319542,-0.336804,0.909759,-0.236541,0.950501,...,-0.050833,0.758747,-0.232952,1.358970,-0.158359,-2.210960,0.075458,-0.124609,3016.90,0
648,648,-0.146285,-0.247111,1.238574,-0.573947,0.174889,-0.101189,0.478846,-0.084924,0.175494,...,-0.117844,-0.283317,-0.063034,1.025291,-0.526151,1.896294,-0.327188,-0.140286,18050.73,0
4013,4013,0.866619,-0.660891,0.560126,-0.413021,0.817982,2.651586,0.006457,0.117251,2.409024,...,-0.097357,0.204393,-0.222745,2.174459,0.891249,-0.513093,-0.167196,0.001351,14865.26,0
4520,4520,-0.066206,-0.191363,1.787259,-0.497660,0.121298,0.314268,0.990624,-0.261463,1.969355,...,-0.308828,-0.545302,-0.122800,0.666108,-0.211244,0.362787,-0.114279,-0.699538,21888.12,0
4677,4677,-0.155119,0.119226,1.759114,0.288951,0.503589,0.659278,0.685873,-0.230543,0.869122,...,-0.306870,-0.535448,-0.120125,-0.127988,-0.914532,-0.375776,0.083934,-0.274560,23467.31,0
3503,3503,0.072355,-0.297863,0.276604,-2.760803,1.726307,1.881421,0.659226,-0.022495,0.961393,...,-0.100252,0.191886,-0.352478,2.244774,0.300668,-2.150268,0.050970,-0.149365,4082.95,0
35,35,-0.014058,-0.169029,1.359264,-0.558402,0.436206,0.525499,0.701020,-0.111349,0.330770,...,-0.083381,0.149756,-0.210874,0.038396,0.076226,-1.382958,-0.325740,-0.038637,6884.95,0
1931,1931,-0.055187,-0.223980,2.051625,-0.631580,0.554488,0.350481,0.897904,-0.275633,0.441163,...,-0.218165,-0.340021,-0.441218,-0.048763,0.608237,0.582138,-0.695679,-1.000044,20116.82,0
806,806,-0.152782,-0.374168,2.662544,-0.145853,0.213275,0.192837,0.325540,-0.104605,0.387578,...,-0.018996,0.354510,-0.152564,0.802878,0.160045,-0.444364,-0.119214,0.164014,17107.63,0
4585,4585,-0.195377,-0.016854,2.849729,0.471522,0.123774,1.462888,0.144013,-0.418227,1.404961,...,0.372086,-0.647578,-0.190788,-0.844716,0.274332,0.732486,-0.151952,0.153853,4683.53,0
3964,3964,-0.144115,-0.022423,1.302133,-0.095245,0.270561,0.673054,0.488380,-0.048350,1.229695,...,-0.180906,0.054328,-0.178346,-0.051061,-0.302647,-0.706486,0.030947,-0.240158,22062.55,0
1724,1724,-0.179962,-0.095155,1.560570,-0.379435,0.172043,0.452594,0.456747,0.014003,0.188775,...,-0.080066,0.080404,-0.021629,0.219200,-0.763285,1.519320,-0.028969,0.192714,19675.22,0
2456,2456,-0.108862,-0.331988,1.678301,-0.869929,0.421639,-0.001326,0.878352,-0.247085,0.628278,...,-0.121950,0.201420,0.069314,0.840151,-0.843311,0.368603,-0.366344,-0.632508,10428.94,0
541,541,-0.478427,0.142165,-0.046838,0.683350,0.067820,-0.404898,-0.206496,0.184366,-0.762935,...,0.098977,-0.075191,-0.481489,0.678900,-0.011520,0.409021,0.075859,-0.447139,1534.53,1
623,623,-0.617111,-1.733888,1.150655,0.207829,0.903533,-0.171524,0.551679,-0.167744,0.338861,...,0.153856,0.369734,1.471004,-0.497633,0.377656,-0.328051,-0.512415,-0.013653,10554.68,1
4920,4920,-0.476617,0.088942,0.326333,0.220370,-0.026730,0.432409,0.646165,-0.240646,0.356997,...,-0.223141,-0.851929,0.153117,-0.127032,-0.334872,-1.353308,-0.192302,-0.470796,2785.98,1
6108,6108,-0.832953,-0.024254,-0.260967,0.323532,-0.117119,-0.589167,-0.390612,-0.207889,0.351702,...,0.120451,0.121804,-0.453630,-0.064071,0.331833,-1.671579,-1.060239,1.939783,15897.18,1
6329,6329,1.020308,0.425645,-0.554113,0.868349,2.367343,-0.360087,1.185828,-0.261569,-0.159521,...,-0.258401,-0.661236,-0.663639,-2.536292,2.502489,1.195597,-0.249226,0.254373,3492.59,1
6331,6331,0.206746,0.706513,-0.816548,1.318995,0.594065,-1.723943,-0.012194,-0.117153,-0.772546,...,0.040282,-0.579715,-0.552521,0.288016,2.501722,1.082153,0.717930,1.136108,3875.51,1
6334,6334,0.215558,0.705195,-0.855171,1.246399,0.886906,-1.135409,-0.025257,-0.082585,-0.898336,...,0.042600,-0.552999,-0.675699,-1.266095,2.715124,1.145445,0.719686,1.095651,4271.95,1
6336,6336,0.376724,0.601380,-0.758334,1.185510,1.078065,-1.071196,0.189482,-0.122113,-0.549752,...,-0.040900,-0.617458,-0.563986,-1.197832,2.369167,1.173497,0.429659,0.874369,13210.79,1
6338,6338,0.369132,0.625338,-0.737571,1.178512,1.012737,-1.230750,0.207340,-0.139856,-0.728694,...,-0.020361,-0.497250,-0.594617,-0.367421,2.476674,1.049491,0.413783,0.869696,20487.28,1
6427,6427,0.629902,0.236773,-0.699889,0.685876,-0.280459,-0.606198,-0.475229,0.101750,0.223472,...,0.126568,0.058486,0.607055,-0.620054,-2.849678,0.772262,0.517924,0.139969,3996.01,1
6446,6446,0.613990,0.270311,-0.687021,0.789924,-0.390662,-1.241988,-0.459287,0.063939,0.397580,...,0.111926,-0.052066,0.738292,1.006317,-3.014063,0.706078,0.526180,0.212196,12162.55,1
6472,6472,0.850258,0.155717,-0.622400,0.636857,-0.157626,-0.607839,-0.308974,0.058629,0.762125,...,0.032063,-0.092669,0.725131,-0.632901,-3.116552,0.802387,0.248282,-0.051260,9890.39,1
6529,6529,-0.317197,0.487606,-0.528588,0.228435,-0.194291,-0.704396,-0.393809,0.216005,-0.125489,...,0.092980,-0.527418,-0.100915,-0.723379,0.118214,0.711221,0.079490,0.220666,10676.68,1
6609,6609,-0.363940,0.523455,-0.478980,0.307721,-0.342845,-1.286550,-0.378567,0.189850,0.076657,...,0.074776,-0.553660,0.022897,0.981187,-0.012128,0.677780,0.430306,0.487964,3732.02,1
6641,6641,0.724142,0.695730,-0.954187,1.471499,0.697196,-1.285905,0.019081,-0.025719,-0.603414,...,0.044347,0.092085,0.223685,-0.393700,-1.635488,0.940607,0.551076,0.258415,5774.97,1
6717,6717,-0.370837,0.895077,-0.777433,1.099162,0.818746,-1.498906,-0.030755,-0.021340,-1.128880,...,0.136425,-0.406104,-0.738997,-0.472904,1.812251,0.715115,0.951329,1.270166,12864.25,1
6719,6719,0.092735,0.749460,-0.893974,1.345562,0.520683,-1.450537,-0.186005,-0.038563,-0.981245,...,0.106480,-0.526781,-0.614924,-0.445029,2.595723,1.112425,0.945736,1.277884,15293.66,1
6734,6734,0.368060,0.332238,-0.776664,0.816366,-0.425367,-0.974103,-0.597242,0.136453,0.117232,...,0.184609,0.016099,0.690432,0.197378,-2.945896,0.711639,0.554634,0.346548,10289.34,1
6774,6774,0.447159,0.285065,-0.743501,0.799755,-0.455830,-0.910555,-0.602560,0.148428,0.105503,...,0.189394,0.087172,0.676899,0.293034,-2.941913,0.737445,0.736277,0.323373,3883.37,1
6820,6820,-0.448980,0.583072,-0.584524,0.338237,-0.378941,-1.016931,-0.521511,0.264374,-0.169523,...,0.147583,-0.490176,-0.024319,0.175258,0.066196,0.683530,0.459922,0.620805,12955.72,1
6870,6870,-0.382306,0.533529,-0.578583,0.359682,-0.377895,-1.010956,-0.525968,0.263894,-0.228639,...,0.156210,-0.501118,-0.036148,0.173146,0.011321,0.676088,0.278393,0.403955,7853.77,1
6882,6882,-0.864163,0.071230,-0.358739,0.767675,-0.316952,-0.123912,-0.579456,-0.042644,0.801038,...,0.085435,0.092670,0.095650,-0.363363,-0.307233,-1.035680,-1.211870,2.038118,11468.71,1
6899,6899,-0.547157,1.115454,-0.979374,1.253370,0.230140,-1.566882,-0.317418,0.283794,-1.140763,...,0.181400,-0.431718,-0.404023,-0.484046,1.636240,0.895599,0.100028,0.632786,1415.95,1
6903,6903,-0.522950,1.100919,-0.975549,1.256962,0.228432,-1.570288,-0.317605,0.295419,-1.156935,...,0.174608,-0.442260,-0.421064,-0.488969,1.643020,0.921023,0.271952,0.643050,1944.95,1
6971,6971,-0.694740,-0.358518,-0.581731,0.897960,-1.334899,2.282266,3.569697,-0.557069,0.077274,...,-0.546221,0.148127,-1.975946,0.370690,-0.708804,0.658524,2.763781,-2.294480,11144.83,1

In [15]:
new_df['Class'].value_counts()

Class
0    25
1    25
Name: count, dtype: int64

In [16]:
new_df.groupby('Class').mean()

,id,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,2892.76,0.088962,-0.222053,1.402564,-0.691858,0.341717,0.394498,0.579052,-0.169638,0.927304,...,-0.113478,-0.102039,-0.052382,-0.129851,0.643858,-0.053491,-0.265220,-0.162619,-0.184061,14286.8288
1,6050.92,-0.040107,0.368566,-0.550948,0.811516,0.184242,-0.793130,0.001613,0.007280,-0.231929,...,0.080662,0.048478,-0.274943,-0.115910,-0.260672,0.131179,0.535532,0.341847,0.470742,8458.3064

In [17]:
X = credit_card_data.drop(columns='Class', axis=1)
Y = credit_card_data['Class']

In [18]:
X = new_df.drop(columns='Class', axis=1)
Y = new_df['Class']

In [19]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

# Model Training

Logistic Regression

In [20]:
model = LogisticRegression()
# training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)

# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)
print('Accuracy on Training data (LR) : ', training_data_accuracy)

# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)
print('Accuracy score on Test Data (LR) : ', test_data_accuracy)

Accuracy on Training data (LR) :  1.0
Accuracy score on Test Data (LR) :  0.9

c:\Users\SHAKIL\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [21]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy_lr = accuracy_score(Y_train, X_train_prediction)
precision_lr = precision_score(Y_train, X_train_prediction)
recall_lr = recall_score(Y_train, X_train_prediction)
f1_lr = f1_score(Y_train, X_train_prediction)

print("Accuracy (LR):", accuracy_lr)
print("Precision (LR):", precision_lr)
print("Recall (LR):", recall_lr)
print("F1 Score (LR):", f1_lr)

Accuracy (LR): 1.0
Precision (LR): 1.0
Recall (LR): 1.0
F1 Score (LR): 1.0

In [22]:
from sklearn.metrics import classification_report

# Generate classification report for test predictions
report = classification_report(Y_test, X_test_prediction)
print(report)

              precision    recall  f1-score   support

           0       0.83      1.00      0.91         5
           1       1.00      0.80      0.89         5

    accuracy                           0.90        10
   macro avg       0.92      0.90      0.90        10
weighted avg       0.92      0.90      0.90        10

SVM

In [23]:
from sklearn import svm

# Support Vector Machine (SVM) model training and evaluation

svm_model = svm.SVC(kernel='linear')
svm_model.fit(X_train, Y_train)

# Predictions on training and test data
X_train_prediction_svm = svm_model.predict(X_train)
X_test_prediction_svm = svm_model.predict(X_test)

# Accuracy scores
training_data_accuracy_svm = accuracy_score(X_train_prediction_svm, Y_train)
test_data_accuracy_svm = accuracy_score(X_test_prediction_svm, Y_test)

print('Accuracy on Training data (SVM):', training_data_accuracy_svm)
print('Accuracy score on Test Data (SVM):', test_data_accuracy_svm)

Accuracy on Training data (SVM): 1.0
Accuracy score on Test Data (SVM): 0.9

In [24]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(Y_train, X_train_prediction_svm)
precision = precision_score(Y_train, X_train_prediction_svm)
recall = recall_score(Y_train, X_train_prediction_svm)
f1 = f1_score(Y_train, X_train_prediction_svm)

print("Accuracy (SVM):", accuracy)
print("Precision (SVM):", precision)
print("Recall (SVM):", recall)
print("F1 Score (SVM):", f1)

Accuracy (SVM): 1.0
Precision (SVM): 1.0
Recall (SVM): 1.0
F1 Score (SVM): 1.0

In [25]:
from sklearn.metrics import classification_report

# Generate classification report for test predictions
report = classification_report(Y_test, X_test_prediction_svm)
print(report)

              precision    recall  f1-score   support

           0       0.83      1.00      0.91         5
           1       1.00      0.80      0.89         5

    accuracy                           0.90        10
   macro avg       0.92      0.90      0.90        10
weighted avg       0.92      0.90      0.90        10

KNN

In [26]:
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, Y_train)

# Accuracy on training data
X_train_prediction_knn = knn_model.predict(X_train)
training_data_accuracy_knn = accuracy_score(X_train_prediction_knn, Y_train)
print('Accuracy on Training data (KNN):', training_data_accuracy_knn)

# Accuracy on test data
X_test_prediction_knn = knn_model.predict(X_test)
test_data_accuracy_knn = accuracy_score(X_test_prediction_knn, Y_test)
print('Accuracy score on Test Data (KNN):', test_data_accuracy_knn)

Accuracy on Training data (KNN): 0.9
Accuracy score on Test Data (KNN): 0.7

In [27]:
accuracy_knn = accuracy_score(Y_train, X_train_prediction_knn)
precision_knn = precision_score(Y_train, X_train_prediction_knn)
recall_knn = recall_score(Y_train, X_train_prediction_knn)
f1_knn = f1_score(Y_train, X_train_prediction_knn)

print("Accuracy (KNN):", accuracy_knn)
print("Precision (KNN):", precision_knn)
print("Recall (KNN):", recall_knn)
print("F1 Score (KNN):", f1_knn)

Accuracy (KNN): 0.9
Precision (KNN): 0.9444444444444444
Recall (KNN): 0.85
F1 Score (KNN): 0.8947368421052632

In [28]:
from sklearn.metrics import classification_report

# Generate classification report for test predictions
report = classification_report(Y_test, X_test_prediction_knn)
print(report)

              precision    recall  f1-score   support

           0       0.67      0.80      0.73         5
           1       0.75      0.60      0.67         5

    accuracy                           0.70        10
   macro avg       0.71      0.70      0.70        10
weighted avg       0.71      0.70      0.70        10

Random Forest

In [29]:
from sklearn.ensemble import RandomForestClassifier

# Create and train the Random Forest model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, Y_train)

# Accuracy on training data
X_train_prediction_rf = rf_model.predict(X_train)
training_data_accuracy_rf = accuracy_score(X_train_prediction_rf, Y_train)
print('Accuracy on Training data (Random Forest):', training_data_accuracy_rf)

# Accuracy on test data
X_test_prediction_rf = rf_model.predict(X_test)
test_data_accuracy_rf = accuracy_score(X_test_prediction_rf, Y_test)
print('Accuracy score on Test Data (Random Forest):', test_data_accuracy_rf)

Accuracy on Training data (Random Forest): 1.0
Accuracy score on Test Data (Random Forest): 0.9

In [30]:
accuracy_rf = accuracy_score(Y_train, X_train_prediction_rf)
precision_rf = precision_score(Y_train, X_train_prediction_rf)
recall_rf = recall_score(Y_train, X_train_prediction_rf)
f1_rf = f1_score(Y_train, X_train_prediction_rf)

print("Accuracy (RF):", accuracy_rf)
print("Precision (RF):", precision_rf)
print("Recall (RF):", recall_rf)
print("F1 Score (RF):", f1_rf)

Accuracy (RF): 1.0
Precision (RF): 1.0
Recall (RF): 1.0
F1 Score (RF): 1.0

In [31]:
from sklearn.metrics import classification_report

# Generate classification report for test predictions
report = classification_report(Y_test, X_test_prediction_rf)
print(report)

              precision    recall  f1-score   support

           0       0.83      1.00      0.91         5
           1       1.00      0.80      0.89         5

    accuracy                           0.90        10
   macro avg       0.92      0.90      0.90        10
weighted avg       0.92      0.90      0.90        10

Decision Tree

In [32]:
from sklearn.tree import DecisionTreeClassifier

# Create and train the Decision Tree model
dtree = DecisionTreeClassifier(random_state=42)
dtree.fit(X_train, Y_train)

# Accuracy on training data
X_train_prediction_dtree = dtree.predict(X_train)
training_data_accuracy_dtree = accuracy_score(X_train_prediction_dtree, Y_train)
print('Accuracy on Training data (Decision Tree):', training_data_accuracy_dtree)

# Accuracy on test data
X_test_prediction_dtree = dtree.predict(X_test)
test_data_accuracy_dtree = accuracy_score(X_test_prediction_dtree, Y_test)
print('Accuracy score on Test Data (Decision Tree):', test_data_accuracy_dtree)

Accuracy on Training data (Decision Tree): 1.0
Accuracy score on Test Data (Decision Tree): 0.7

In [33]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy_dtree = accuracy_score(Y_train, X_train_prediction_dtree)
precision_dtree = precision_score(Y_train, X_train_prediction_dtree)
recall_dtree = recall_score(Y_train, X_train_prediction_dtree)
f1_dtree = f1_score(Y_train, X_train_prediction_dtree)

print("Accuracy (DT):", accuracy_dtree)
print("Precision (DT):", precision_dtree)
print("Recall (DT):", recall_dtree)
print("F1 Score (DT):", f1_dtree)

Accuracy (DT): 1.0
Precision (DT): 1.0
Recall (DT): 1.0
F1 Score (DT): 1.0

In [34]:
from sklearn.metrics import classification_report

# Generate classification report for test predictions
report = classification_report(Y_test, X_test_prediction_dtree)
print(report)

              precision    recall  f1-score   support

           0       0.75      0.60      0.67         5
           1       0.67      0.80      0.73         5

    accuracy                           0.70        10
   macro avg       0.71      0.70      0.70        10
weighted avg       0.71      0.70      0.70        10

XGBoost

In [35]:
from xgboost import XGBClassifier

# Create and train the XGBoost model
xgb_model = XGBClassifier(eval_metric='logloss', random_state=42)
xgb_model.fit(X_train, Y_train)

# Accuracy on training data
X_train_prediction_xgb = xgb_model.predict(X_train)
training_data_accuracy_xgb = accuracy_score(X_train_prediction_xgb, Y_train)
print('Accuracy on Training data (XGBoost):', training_data_accuracy_xgb)

# Accuracy on test data
X_test_prediction_xgb = xgb_model.predict(X_test)
test_data_accuracy_xgb = accuracy_score(X_test_prediction_xgb, Y_test)
print('Accuracy score on Test Data (XGBoost):', test_data_accuracy_xgb)

Accuracy on Training data (XGBoost): 1.0
Accuracy score on Test Data (XGBoost): 0.9

In [36]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy_xgb = accuracy_score(Y_train, X_train_prediction_xgb)
precision_xgb = precision_score(Y_train, X_train_prediction_xgb)
recall_xgb = recall_score(Y_train, X_train_prediction_xgb)
f1_xgb = f1_score(Y_train, X_train_prediction_xgb)

print("Accuracy (XGBoost):", accuracy_xgb)
print("Precision (XGBoost):", precision_xgb)
print("Recall (XGBoost):", recall_xgb)
print("F1 Score (XGBoost):", f1_xgb)

Accuracy (XGBoost): 1.0
Precision (XGBoost): 1.0
Recall (XGBoost): 1.0
F1 Score (XGBoost): 1.0

In [37]:
from sklearn.metrics import classification_report

# Generate classification report for test predictions
report = classification_report(Y_test, X_test_prediction_xgb)
print(report)

              precision    recall  f1-score   support

           0       0.83      1.00      0.91         5
           1       1.00      0.80      0.89         5

    accuracy                           0.90        10
   macro avg       0.92      0.90      0.90        10
weighted avg       0.92      0.90      0.90        10

In [38]:
from sklearn.ensemble import AdaBoostClassifier

# Create and train the AdaBoost model
ada_model = AdaBoostClassifier(n_estimators=100, random_state=42)
ada_model.fit(X_train, Y_train)

# Accuracy on training data
X_train_prediction_ada = ada_model.predict(X_train)
training_data_accuracy_ada = accuracy_score(X_train_prediction_ada, Y_train)
print('Accuracy on Training data (AdaBoost):', training_data_accuracy_ada)

# Accuracy on test data
X_test_prediction_ada = ada_model.predict(X_test)
test_data_accuracy_ada = accuracy_score(X_test_prediction_ada, Y_test)
print('Accuracy score on Test Data (AdaBoost):', test_data_accuracy_ada)

Accuracy on Training data (AdaBoost): 1.0
Accuracy score on Test Data (AdaBoost): 1.0

In [39]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

ada_train_pred = ada_model.predict(X_train)

accuracy_ada = accuracy_score(Y_train, ada_train_pred)
precision_ada = precision_score(Y_train, ada_train_pred)
recall_ada = recall_score(Y_train, ada_train_pred)
f1_ada = f1_score(Y_train, ada_train_pred)

print("Accuracy (AdaBoost):", accuracy_ada)
print("Precision (AdaBoost):", precision_ada)
print("Recall (AdaBoost):", recall_ada)
print("F1 Score (AdaBoost):", f1_ada)

Accuracy (AdaBoost): 1.0
Precision (AdaBoost): 1.0
Recall (AdaBoost): 1.0
F1 Score (AdaBoost): 1.0

In [40]:
from sklearn.metrics import classification_report

# Generate classification report for test predictions
report = classification_report(Y_test, X_test_prediction_ada)
print(report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       1.00      1.00      1.00         5

    accuracy                           1.00        10
   macro avg       1.00      1.00      1.00        10
weighted avg       1.00      1.00      1.00        10

In [41]:
from sklearn.ensemble import GradientBoostingClassifier

# Create and train the Gradient Boosting model
gb_model = GradientBoostingClassifier(n_estimators=100, random_state=42)
gb_model.fit(X_train, Y_train)

# Accuracy on training data
X_train_prediction_gb = gb_model.predict(X_train)
training_data_accuracy_gb = accuracy_score(X_train_prediction_gb, Y_train)
print('Accuracy on Training data (GB):', training_data_accuracy_gb)

# Accuracy on test data
X_test_prediction_gb = gb_model.predict(X_test)
test_data_accuracy_gb = accuracy_score(X_test_prediction_gb, Y_test)
print('Accuracy score on Test Data (GB):', test_data_accuracy_gb)

Accuracy on Training data (GB): 1.0
Accuracy score on Test Data (GB): 0.9

In [42]:
# Predictions on training data for Gradient Boosting
X_train_prediction_gb = gb_model.predict(X_train)

# Calculate metrics for Gradient Boosting
accuracy_gb = accuracy_score(Y_train, X_train_prediction_gb)
precision_gb = precision_score(Y_train, X_train_prediction_gb)
recall_gb = recall_score(Y_train, X_train_prediction_gb)
f1_gb = f1_score(Y_train, X_train_prediction_gb)

print("Accuracy (GB):", accuracy_gb)
print("Precision (GB):", precision_gb)
print("Recall (GB):", recall_gb)
print("F1 Score (GB):", f1_gb)

Accuracy (GB): 1.0
Precision (GB): 1.0
Recall (GB): 1.0
F1 Score (GB): 1.0

In [43]:
from sklearn.metrics import classification_report

# Generate classification report for test predictions
report = classification_report(Y_test, X_test_prediction_gb)
print(report)

              precision    recall  f1-score   support

           0       0.83      1.00      0.91         5
           1       1.00      0.80      0.89         5

    accuracy                           0.90        10
   macro avg       0.92      0.90      0.90        10
weighted avg       0.92      0.90      0.90        10

In [44]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

# Build a simple feedforward neural network
model_keras = Sequential([
    Dense(32, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])

model_keras.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
history = model_keras.fit(X_train, Y_train, epochs=100, batch_size=32, validation_data=(X_test, Y_test), verbose=0)

# Evaluate on training data
train_loss, train_acc_keras = model_keras.evaluate(X_train, Y_train, verbose=0)
print('Keras Model Accuracy on Training data:', train_acc_keras)

# Evaluate on test data
test_loss, test_acc_keras = model_keras.evaluate(X_test, Y_test, verbose=0)
print('Keras Model Accuracy on Test data:', test_acc_keras)

c:\Users\SHAKIL\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Keras Model Accuracy on Training data: 0.8500000238418579
Keras Model Accuracy on Test data: 0.8999999761581421